<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/cardpack.glb --transform
-->

<script>
	import { T, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import * as THREE from 'three'
	import { Group } from 'three'

	export const ref = new Group()

	const gltf = useGltf('/cardpack-transformed.glb', { useDraco: true })

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Box006.geometry}
			material={gltf.materials.wire_135059008}
			rotation={[0, 0, 0]}
		>
			<T.MeshPhysicalMaterial
				iridescence={0.9}
				iridescenceIOR={2.5}
				iridescenceThicknessRange={[100, 800]}
				roughness={0.125}
				metalness={1}
				clearcoat={1}
				clearcoatRoughness={0.1}
				sheen={1}
				sheenRoughness={0.33}
				sheenColor={new THREE.Color(0xaaffff)}
				envMapIntensity={1.5}
			/>
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
