<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/cardpack3.glb --transform
-->

<script>
	import { T, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'
	import * as THREE from 'three'
	import { Group } from 'three'

	export const ref = new Group()

	const gltf = useGltf('/cardpack3-transformed.glb', { useDraco: true })

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={0.01875} rotation={[Math.PI / 2, 0, 0]}>
			<T.Mesh geometry={gltf.nodes.Mesh.geometry}>
				<T.MeshPhysicalMaterial
					{...gltf.materials.pack_texture_02}
					map={gltf.materials.pack_texture_02.map}
					iridescenceMap={gltf.materials.pack_texture_02.map}
					metalnessMap={gltf.materials.pack_texture_02.map}
					iridescence={200}
					iridescenceIOR={2.5}
					iridescenceThicknessRange={[100, 800]}
					roughness={0.25}
					metalness={1.05}
					clearcoat={1}
					clearcoatRoughness={0.25}
					sheen={1}
					sheenRoughness={0.33}
					sheenColor={new THREE.Color(0xaaffff)}
					envMapIntensity={1.5}
				/>
			</T.Mesh>
			<T.Mesh geometry={gltf.nodes.Mesh_1.geometry}>
				<T.MeshPhysicalMaterial
					{...gltf.materials.pack_texture_02_back}
					iridescence={0.9}
					iridescenceIOR={2.5}
					iridescenceThicknessRange={[100, 800]}
					roughness={0.125}
					metalness={1}
					clearcoat={1}
					clearcoatRoughness={0.1}
					sheen={1}
					sheenRoughness={0.33}
					sheenColor={new THREE.Color(0xaaffff)}
					envMapIntensity={1.5}
				/>
			</T.Mesh>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
